name: Buildy McBuildface
on: [push]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: run
            uses: cedrickring/golang-action@1.5.2
            with:
              args:
                - go test ./cmd/repository
                - go build

